/**
 * Guided setup wizard. Run with `npm run setup`.
 *
 * Collects the two required values (Lambda API key + PEM path), picks the agent
 * transport, optionally verifies the key against the Lambda API, then writes a
 * minimal `.env.local`. Everything else uses code defaults.
 */

import { existsSync } from "node:fs";
import { copyFile, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import * as p from "@clack/prompts";
import { lambdaFetch } from "../src/lib/lambda";

const ENV_LOCAL = path.resolve(process.cwd(), ".env.local");
const ENV_FALLBACK = path.resolve(process.cwd(), ".env");
const API_KEYS_URL = "https://cloud.lambda.ai/api-keys";

type Transport = "http" | "stdio";

/** Pull an existing value for a key out of a dotenv-style file (best effort). */
function readEnvValue(contents: string, key: string): string {
  for (const line of contents.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    if (trimmed.slice(0, eq).trim() === key) {
      return trimmed.slice(eq + 1).trim();
    }
  }
  return "";
}

async function loadExistingEnv(): Promise<Record<string, string>> {
  const file = existsSync(ENV_LOCAL)
    ? ENV_LOCAL
    : existsSync(ENV_FALLBACK)
      ? ENV_FALLBACK
      : null;
  if (!file) return {};
  try {
    const contents = await readFile(file, "utf8");
    return {
      LAMBDA_API_KEY: readEnvValue(contents, "LAMBDA_API_KEY"),
      LAMBDA_SSH_PEM_PATH: readEnvValue(contents, "LAMBDA_SSH_PEM_PATH"),
      LAMBDA_MCP_TRANSPORT: readEnvValue(contents, "LAMBDA_MCP_TRANSPORT"),
    };
  } catch {
    return {};
  }
}

function buildEnvFile(opts: {
  apiKey: string;
  pemPath: string;
  transport: Transport;
}): string {
  const lines: string[] = [
    "# Generated by `npm run setup`. Safe to edit by hand.",
    "# Full reference for every supported variable: docs/configuration.md",
    "",
    "# --- Required ---",
    "# Lambda Cloud API key (https://cloud.lambda.ai/api-keys).",
    `LAMBDA_API_KEY=${opts.apiKey}`,
    "",
    "# Absolute path to the .pem matching your Lambda SSH public key.",
    `LAMBDA_SSH_PEM_PATH=${opts.pemPath}`,
    "",
  ];

  if (opts.transport === "http") {
    lines.push(
      "# --- Agent transport: Poke (HTTP) ---",
      "# MCP serves http://127.0.0.1:8080/mcp; connect Poke with:",
      '#   npx poke@latest tunnel http://127.0.0.1:8080/mcp -n "Local dev mcp"',
      "LAMBDA_MCP_TRANSPORT=http",
      ""
    );
  } else {
    lines.push(
      "# --- Agent transport: Cursor (stdio) ---",
      "# stdio is the default when LAMBDA_MCP_TRANSPORT is unset; your editor",
      "# launches the MCP via `npm run mcp`. Nothing extra needed here.",
      ""
    );
  }

  return lines.join("\n");
}

async function main(): Promise<void> {
  console.clear();
  p.intro("Lambda Cloud MCP — guided setup");

  const existing = await loadExistingEnv();
  const hasExisting = existsSync(ENV_LOCAL);

  if (hasExisting) {
    const overwrite = await p.confirm({
      message: ".env.local already exists. Update it now?",
      initialValue: true,
    });
    if (p.isCancel(overwrite) || !overwrite) {
      p.cancel("Left .env.local untouched.");
      process.exit(0);
    }
    await copyFile(ENV_LOCAL, `${ENV_LOCAL}.bak`);
    p.log.info("Backed up existing file to .env.local.bak");
  }

  const apiKey = await p.password({
    message: `Lambda Cloud API key  (get one at ${API_KEYS_URL})`,
    validate: (value) => {
      if (!value || !value.trim()) return "API key is required.";
      return undefined;
    },
  });
  if (p.isCancel(apiKey)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }
  const apiKeyValue = apiKey.trim();

  const verify = await p.confirm({
    message: "Verify this key against the Lambda API now?",
    initialValue: true,
  });
  if (!p.isCancel(verify) && verify) {
    const s = p.spinner();
    s.start("Checking Lambda API…");
    try {
      const res = await lambdaFetch("/instance-types", { apiKey: apiKeyValue });
      if (res.ok) {
        s.stop("API key verified.");
      } else if (res.status === 401 || res.status === 403) {
        s.stop("Lambda rejected the key (401/403).");
        const proceed = await p.confirm({
          message: "Save it anyway and continue?",
          initialValue: false,
        });
        if (p.isCancel(proceed) || !proceed) {
          p.cancel("Setup cancelled. Double-check your key and re-run npm run setup.");
          process.exit(0);
        }
      } else {
        s.stop(`Could not verify (HTTP ${res.status}). Continuing.`);
      }
    } catch {
      s.stop("Could not reach the Lambda API (network?). Continuing.");
    }
  }

  const pemDefault =
    existing.LAMBDA_SSH_PEM_PATH || "";
  const pemPath = await p.text({
    message: "Absolute path to your .pem SSH key",
    placeholder: "C:\\Users\\you\\.ssh\\lambda-key.pem",
    initialValue: pemDefault,
    validate: (value) => {
      if (!value || !value.trim()) return "PEM path is required.";
      return undefined;
    },
  });
  if (p.isCancel(pemPath)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }
  const pemValue = pemPath.trim();
  if (!existsSync(pemValue)) {
    p.log.warn(
      `No file found at that path yet. Saving it anyway — make sure it exists before launching instances.`
    );
  }

  const transport = await p.select({
    message: "How will agents connect to the MCP server?",
    initialValue:
      existing.LAMBDA_MCP_TRANSPORT?.toLowerCase() === "stdio"
        ? "stdio"
        : "http",
    options: [
      {
        value: "http",
        label: "Poke (HTTP) — recommended",
        hint: "text-message control; one `npm run dev` runs UI + MCP",
      },
      {
        value: "stdio",
        label: "Cursor / editor (stdio)",
        hint: "your editor launches the MCP itself",
      },
    ],
  });
  if (p.isCancel(transport)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }

  const envContents = buildEnvFile({
    apiKey: apiKeyValue,
    pemPath: pemValue,
    transport: transport as Transport,
  });
  await writeFile(ENV_LOCAL, `${envContents}\n`, "utf8");
  p.log.success("Wrote .env.local");

  const nextSteps =
    transport === "http"
      ? [
          "1. npm run dev          (starts the UI + MCP together)",
          "2. open http://localhost:3000",
          '3. npx poke@latest tunnel http://127.0.0.1:8080/mcp -n "Local dev mcp"',
        ].join("\n")
      : [
          "1. npm run dev:ui       (starts just the UI)",
          "2. open http://localhost:3000",
          "3. point your editor's MCP config at `npm run mcp` in this folder",
        ].join("\n");

  p.note(nextSteps, "Next steps");
  p.outro("Setup complete.");
}

main().catch((err) => {
  p.log.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
